Release V1
apibara/starknet-react pull request #268
Opened 2023-06-25 19:31 UTC by fracek

The goal of this PR is to prepare for the v1 release, which brings Starknet.js v5 compatibility.

2023-06-27 08:21 UTC, fracek commented
Need to add a changelog before we can release

2023-06-29 19:51 UTC, fracek commented
Hey @dhruvkelawala , if you have time to give this a quick look it would be great!

2023-06-29 20:21 UTC, dhruvkelawala commented
Will review it tomorrow! Thanks!

2023-07-03 11:13 UTC, dhruvkelawala requested changes

2023-07-03 11:13 UTC, dhruvkelawala commented on packages/core/src/hooks/receipt.ts
> +import { Chain, useNetwork } from '..'
```suggestion
import { Chain, useNetwork } from './network'
```

2023-07-03 11:13 UTC, dhruvkelawala commented on packages/core/src/hooks/transaction.ts
> +import { Chain } from '..'
```suggestion
import { useNetwork, Chain } from './network'
```

2023-07-03 11:13 UTC, dhruvkelawala commented on packages/core/src/providers/starknet.tsx
> +    network: constants.NetworkName.SN_GOERLI,
Let's default to mainnet as we discussed?

2023-07-03 11:13 UTC, dhruvkelawala commented on packages/core/src/providers/starknet.tsx
> +        (connector) => connector.id === lastConnectedConnectorId
This looks much better

2023-07-03 11:14 UTC, dhruvkelawala commented
Just some minor changes required, otherwise lgtm!

2023-07-03 20:19 UTC, fracek commented
Thank you! Tomorrow I'll double check everything and release this.

2023-07-04 08:25 UTC, merged