doc: update 3 hooks
apibara/starknet-react pull request #345
Opened 2023-11-18 22:33 UTC by okhaimie-dev

## Changes

- Updated the documentation for 3 hooks
  - useContractWrite
  - useSignTypedData
  - useStarkName

2023-11-19 09:58 UTC, fracek requested changes

2023-11-19 09:58 UTC, fracek commented on website/content/hooks/mutation/useSignTypedData.mdx
>  Hook to disconnect the currently connected wallet.
```suggestion
Request user to sign a piece of data.
```

2023-11-19 09:58 UTC, fracek commented on website/content/hooks/mutation/useSignTypedData.mdx
> +<a href="https://gist.github.com/okhaimie-dev/5bd0ee3eab8b2b76d016f5522569820f" target="_blank">Example Json Data</a>
```suggestion
You can read more about Starknet signatures and the meaning of the arguments [on the Starknet.js documentation](https://www.starknetjs.com/docs/guides/signature/).
```

2023-11-19 09:58 UTC, fracek commented on website/content/hooks/mutation/useSignTypedData.mdx
> +			{isPending ? <p>Loading...</p> : <p>Sign Message</p>}
```suggestion
			{isPending ? <p>Waiting for wallet...</p> : <p>Sign Message</p>}
```

2023-11-19 16:46 UTC, okhaimie-dev commented
@fracek I committed the suggestions. Let me know if there is anything else to get to the finish line.

2023-11-20 11:22 UTC, fracek approved these changes
Looks good! Thank you!

2023-11-20 11:22 UTC, merged