fix: wallet icons when not found
apibara/starknet-react pull request #377
Opened 2023-12-14 18:15 UTC by mgavillo

fix to issue #370 

I kept the wallet not found in case there is other wallets

2023-12-14 18:53 UTC, fracek requested changes
Looks good. Only a small change required. Can you also add a changelog (patch bump) so that I can make a release?

2023-12-14 18:53 UTC, fracek commented on packages/core/src/connectors/injected.ts
> +  "Argent": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI0LjAuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAg
Can you use the wallet id as key?

2023-12-14 21:58 UTC, mgavillo commented on packages/core/src/connectors/injected.ts
> +  "Argent": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI0LjAuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAg
done

2023-12-15 10:30 UTC, fracek approved these changes
Thank you for the changes!

2023-12-15 10:30 UTC, merged