feat(core): Add "watch asset" hook and implement corresponding tests
apibara/starknet-react pull request #490
Opened 2024-08-28 10:53 UTC by deeseeker

![Screenshot 2024-08-28 100943](https://github.com/user-attachments/assets/68ba56a2-94e2-4185-9475-41f2ae3849b1)
![Screenshot 2024-08-28 101502](https://github.com/user-attachments/assets/8d07bb1a-f944-420b-945d-ec5fa0d20d79)
I am getting this error after testing. Could you please review the code?

2024-08-29 12:57 UTC, fracek commented on packages/core/tsconfig.vitest-temp.json
Please check what you commit before pushing.

2024-08-29 12:58 UTC, fracek commented
Thank you for this. Can you make sure the tests pass before pushing?

2024-08-30 18:27 UTC, jaipaljadeja requested changes
The tests currently work with Mock Connector ([mock.ts](https://github.com/apibara/starknet-react/blob/main/packages/core/src/connectors/mock.ts)).
Please take note of the request method. Add a case for watchAsset, similar to `wallet_addStarknetChain` and ensure that it returns a boolean. Be sure to double-check what gets returned for this case referring the @starknet-io/types-js package.

Additionally, refer to the test for `useAddChain`, and rewrite the test accordingly.

2024-09-01 10:45 UTC, fracek approved these changes
Looks good now, thank you!

2024-09-01 11:23 UTC, jaipaljadeja approved these changes
Looks good to me!

2024-09-01 12:32 UTC, merged

2024-09-01 20:39 UTC, deeseeker commented
> Looks good now, thank you!

It's an honor sir!