(wip) feat:kakarot connectors
apibara/starknet-react pull request #519
Opened 2024-10-22 18:08 UTC by enitrat

Initial work on implementing a wrapper around EVM connectors through Kakarot

2024-10-26 10:34 UTC, fracek approved these changes

2024-10-26 10:34 UTC, fracek commented on packages/kakarot/README.md
> +import { kakarotConnectors } from '@starknet-react/kakarot`
```suggestion
import { kakarotConnectors } from "@starknet-react/kakarot"
```

2024-10-26 10:35 UTC, fracek requested changes
Looks good. Can you fix the CI and the README so that I can merge and make a release?

2024-10-28 14:52 UTC, Eikix commented on packages/kakarot/src/kakarot.ts
> +export class KakarotConnector extends Connector {
as I understand, some methods comply with starknet wallet spec, via starknet react, other methods comply with Eth EIP1193

Should we add in docstring methods linked with Starknet and others for Eth?

2024-10-29 10:00 UTC, fracek commented on packages/core/src/connectors/base.ts
> +  }): Promise<ConnectorData>;
```suggestion
  abstract connect(parameters: {
    chainIdHint?: bigint;
  } = {}): Promise<ConnectorData>;
```

2024-10-29 10:14 UTC, fracek approved these changes

2024-10-29 10:14 UTC, merged